# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build

    pool:
      vmImage: $(vmImageName)

    steps:

    - task: DotNetCoreCLI@2
      displayName: 'Restore solution'
      inputs:
        command: 'restore'
        projects: '**/*.sln'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName: Build RecipeService
      inputs:
        command: 'build'
        projects: '**/RecipeService/RecipeService.csproj'

    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'

    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        command: 'login'
        addPipelineData: false

    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'robert8034/recipeservice'
        command: 'buildAndPush'
        Dockerfile: 'RecipeService/Dockerfile'
        tags: 'latest'
        addPipelineData: false
        
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        command: 'logout'
        addPipelineData: false
