# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

pool:
  vmImage: 'windows-latest'

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '7355d863-df2d-4022-a2ec-3ac00fee0c18'
  imageRepository: 'robertmealz'
  containerRegistry: 'mealzcontainerregistry.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'mealzcontainerregistryfd4f-auth'
  azureSubscriptionEndpoint: 'Azure for Students(23f4b68b-d9db-4cd7-ad04-8d84881a8c95)'
  azureResourceGroup: 'Mealz'
  kubernetesCluster: 'MealzCluster'

  buildConfiguration: 'Release'
  buildPlatform: 'any cpu'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: 'Mealz.sln'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud Mealz'
    organization: 'robert8034'
    scannerMode: 'MSBuild'
    projectKey: 'Robert8034_Mealz'
    projectName: 'Mealz'

- task: VSBuild@1
  displayName: 'Build solution **\*.sln'
  inputs:
    solution: 'Mealz.sln'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     **\$(BuildConfiguration)\*Test*.dll
     !**\obj\**
    codeCoverageEnabled: true
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: Kubernetes@1
  displayName: kubectl apply using configFile
  inputs:
    connectionType: Azure Resource Manager
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureResourceGroup: $(azureResourceGroup)
    kubernetesCluster: $(kubernetesCluster)
    command: apply
    useConfigurationFile: true
    configuration: 'mealzDeployment.yml'