version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile

  authentication:
    image: ${DOCKER_REGISTRY-}authentication
    build:
      context: .
      dockerfile: Authentication/Dockerfile

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    container_name: RabbitMQ
    ports:
        - "15672:15672"
        - "5672:5672"
    expose:
        - 15672
        - 5672

  authdb:
    image: "mcr.microsoft.com/mssql/server"
    container_name: AuthDB
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
        - "5673:5672"
        - "1433:1433"
    expose:
        - 5673
        - 1433

  userdb:
    image: "mcr.microsoft.com/mssql/server"
    container_name: UserDB
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
        - "5674:5672"
        - "1434:1433"
    expose:
        - 5674
        - 1434