version: '3.4'

services:
  apigateway:
    image: robert8034/apigateway:dev
    tty: true
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
        - "50000:80"
        - "50001:443"

  authentication:
    image: robert8034/authentication:dev
    tty: true
    build:
      context: .
      dockerfile: Authentication/Dockerfile
    
  userservice:
    image: robert8034/userservice:dev
    tty: true
    build:
      context: .
      dockerfile: UserService/Dockerfile
   
  recipeservice:
    image: robert8034/recipeservice:dev
    tty: true
    build:
      context: .
      dockerfile: RecipeService/Dockerfile

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    container_name: RabbitMQ
    ports:
        - "15672:15672"
        - "5672:5672"
    expose:
        - 15672
        - 5672

  authdb:
    image: "mcr.microsoft.com/mssql/server"
    container_name: AuthDB
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
        - "5673:5672"
        - "1433:1433"
    expose:
        - 1433

  userdb:
    image: "mcr.microsoft.com/mssql/server"
    container_name: UserDB
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
        - "5674:5672"
        - "1434:1433"

  recipedb:
    image: "mcr.microsoft.com/mssql/server"
    container_name: RecipeDB
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
        - "5675:5672"
        - "1435:1433"
  