version: '3.4'

services:
  apigateway:
    image: robert8034/apigateway:dev-v1
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
        - "50002:80"
        - "50003:443"

  authentication:
    image: robert8034/authentication:dev-v1
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Authentication/Dockerfile
    ports:
        - "50010:80"
        - "50011:443"
    
  userservice:
    image: robert8034/userservice:dev-v1
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
        - "50020:80"
        - "50021:443"
   
  recipeservice:
    image: robert8034/recipeservice:dev-v1
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: RecipeService/Dockerfile
    ports:
        - "50030:80"
        - "50031:443"
    environment:
        MongoDB__Host: mongo
    depends_on:
        - mongo

  moderationservice:
    image: robert8034/moderationservice:dev-v1
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ModerationService/Dockerfile
    ports:
        - "50040:80"
        - "50041:443"

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    container_name: RabbitMQ
    ports:
        - "15672:15672"
        - "5672:5672"
    expose:
        - 15672
        - 5672

  authdb:
    image: "mcr.microsoft.com/mssql/server"
    container_name: AuthDB
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
        - "5673:5672"
        - "1433:1433"
    expose:
        - 1433

  userdb:
    image: "mcr.microsoft.com/mssql/server"
    container_name: UserDB
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
        - "5674:5672"
        - "1443:1433"

  moderationdb:
    image: "mcr.microsoft.com/mssql/server"
    container_name: ModerationDB
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
        - "5675:5672"
        - "1453:1433"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
    - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
